### ISSUE TITLE
Problema em indicador de navegação

### ISSUE THREAD

**Issue by 0no** [LucasMRomao/ibcamposbrancos#4]
Quando clico em uma data para ver o vídeo do culto a data fica com o background azul indicando que foi selecionado, contudo quando clico em outra data a anterior não volta a ficar branca novamente.

Veja:

![image](https://user-images.githubusercontent.com/8201698/179358924-e14cc900-86f3-44d6-8470-82022095c50d.png)

**Comment by LucasMRomao** [comment]
Resolvido :))
https://user-images.githubusercontent.com/108697755/179617563-dc598831-788f-4da6-b257-31588edd827c.mp4
