### ISSUE TITLE
Melhoria remoção de espaço em branco

### ISSUE THREAD

**Issue by 0no** [LucasMRomao/ibcamposbrancos#5]
Não seria interessante que a altura da lista de datas chegasse até o rodapé?
Eliminando o espaço em branco

![image](https://user-images.githubusercontent.com/8201698/179359085-38ed3c29-a85d-4b3e-930d-6341b460922e.png)

**Comment by LucasMRomao** [comment]
O que achou? ^^

![image](https://user-images.githubusercontent.com/108697755/179616389-ed62ff4c-9632-4029-82f3-408ae2c116d4.png)
